#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source
ynh_setup_source --dest_dir="$install_dir"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# NODEJS BUILD
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"
    ynh_config_add --template=".env.production" --destination="$install_dir/.env.production"
    ynh_hide_warnings ynh_exec_as_app sed -i "s/'safari12'/'safari14'/g" "$install_dir/vite.config.mjs"
    ynh_hide_warnings ynh_exec_as_app npm install
    ynh_hide_warnings ynh_exec_as_app npm update
    ynh_hide_warnings ynh_composer_exec install
    ynh_hide_warnings ynh_exec_as_app npm run build
popd

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
